### ISSUE TITLE
[Feature] 로그인 후 개인설정 화면 구현

### ISSUE THREAD

**Issue by Chaem03** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#131]
## ✔️ Issue

로그인 후 개인설정 화면 구현 및 디테일 디자인 수정

## 📝 To-do

- [x] 로그인 후 개인설정 화면 구현
- [x] 연예인 개별페이지 점수 빼고 새로운 요소 넣기
- [x] 마이페이지 나의 최애 디자인 수정

## 🛠 Working time
>3h
