### ISSUE TITLE
[Feature] 캘린더 API 연결 및 UI 개선

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#166]
## ✔️ Issue
> 캘린더 API 연결 및 UI 개선을 진행합니다.

## 📝 To-do

- [x] 요청한 달 데이터 불러와서 캘린더에 표시
- [x] 날짜별 데이터 확인
- [x] 날짜별 루틴 완료 시 등록
- [x] 루틴 확인 UI 구현
- [x] 퍼스널 스케쥴 등록
## 🛠 Working time

> 1d
