### ISSUE TITLE
[Fix] 캘린더 페이지 에러 수정

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#269]
## ✔️ Issue

> 캘린더 페이지에서 발생하는 각종 에러를 수정합니다.

## 📝 To-do

- [x] 모달 닫기 상황에서 캘린더 에러 이슈
- [x] 각 요소별 gap 등 제공
- [x] Default To-do View 사이즈 확보 및 데이터 양에 따른 스크롤 뷰 구현
- [x] 데이터 없으면, "새 루틴을 등록해보세요!"
- [x] 등록 View 수정
- [ ] 완료 시 애니메이션 모달 구현

## 🛠 Working time

> 3h
