### ISSUE TITLE
[Feature] 목표기간 설정 기능 구현

### ISSUE THREAD

**Issue by Chaem03** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#28]
## ✔️ Issue

>루틴박스 속 plus버튼 눌렀을 때 이동하는 목표기간 설정 기능 구현

## 📝 To-do

- [x] react-date-range 라이브러리 테스트
- [x] 연예인 개인 페이지 구현
- [x] 목표기간 설정 기능 구현

## 🛠 Working time

>1d
