### ISSUE TITLE
[Design] 메인페이지 및 테마페이지 디자인 수정  

### ISSUE THREAD

**Issue by Chaem03** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#292]
## ✔️ Issue

>메인페이지 디테일디자인 수정 할 예정입니다.

## 📝 To-do

- [ ] 배너슬라이드 너비 조정
- [ ] 배너 슬라이드 콘테이너 수정
- [ ] 테마페이지 디자인 수정 

## 🛠 Working time

>3h
