### ISSUE TITLE
[Fix] 로그인 & 회원가입 페이지 에러 수정

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#296]
## ✔️ Issue

> 로그인과 회원가입 페이지 에러를 수정합니다.

## 📝 To-do

- [x] 화면비율에 따라서 정렬 맞추기3
- [ ] 맞춤형루틴 박스 크기 텍스트에 따라 다르게 설정
- [x] 맞춤형루틴 POST 에러 수정
- [x] 이용약관, 개인정보처리방침 각각 페이지 분리
- [x] 체크박스 이미지 변경
- [x] 약관 체크 시 버튼 활성화

## 🛠 Working time

> 2h
