### ISSUE TITLE
[Design] 검색페이지, 랜덤주사위 페이지 디자인 수정

### ISSUE THREAD

**Issue by Chaem03** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#310]
## ✔️ Issue

>검색페이지, 랜덤주사위 페이지 디자인 수정

## 📝 To-do

- [ ] 검색페이지 뒤로가기 버튼 구현
- [ ] 랜덤루틴 레이아웃 수정
- [ ] 화면 스크롤 가능하도록 화면구조 조정
- [ ] 버튼 활성화 기능 구현
