### ISSUE TITLE
[Design] 캘린더 페이지 디자인 수정

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#328]
## ✔️ Issue

>  캘린더 페이지 디자인 수정

## 📝 To-do

- [x] To do뷰 + 버튼 확장 기능
- [x] 체크 눌렀을 때 바로 바뀌게
- [x] 체크 후 완료 모달 나타내기
- [x] 루틴에 스타이름 추가 및 스타 페이지 연동

## 🛠 Working time

> 2h
