### ISSUE TITLE
[Fix] 기록페이지 유저 UI 개선

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#38]
## ✔️ Issue

> 기록페이지의 캘린더, 하단 바 등 유저 UI를 개선합니다.

## 📝 To-do

- [x] 커스텀 캘린더 컴포넌트 디자인 보완
- [x] 기록페이지 레이아웃 수정
- [x] 하단 바 에러 수정

## 🛠 Working time

> 5h
