### ISSUE TITLE
[Design] 프론트엔드 개발환경 구현

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#7]
## ✔️ Issue

> 프론트엔드 협업을 위한 초기 컴포넌트 설계 및 스타일링을 진행합니다.

## 📝 To-do

- [x] theme.js 세팅
- [x] globalStyle.js 세팅
- [x] 초기 레이아웃 설계

## 🛠 Working time

> 2h
