### ISSUE TITLE
[Feature] 로그인 - 회원가입 간 API 연동

### ISSUE THREAD

**Issue by sayyyho** [LikeLion-at-DGU/2024-Hackathon-4-STAR.T-Frontend#74]
## ✔️ Issue

> 카카오 로그인 이후에 회원가입 유무 체크 후 메인 페이지로 이동하는 로직을 구현합니다.

## 📝 To-do

- [x] 회원가입 기능 구현
- [x] 회원가입 유무 API 연결
- [x] 로딩페이지 구현
- [x] 각 페이지 loader 활성화

## 🛠 Working time

> 1d
